### ISSUE TITLE
"show interfaces extensive" timeout with large interfaces list

### ISSUE THREAD

**Issue by fdebonneval** [dgarros/py-metric-collector#46]
Our backbone routers (MX480 with RE2) have
* 170-200 interfaces
* 9-10K units

"show interfaces extensive" can take up to ~1 minute and 400K lines in XML.
The scheduler hits his default timeout so values from the parser get lost.

Would it be possible to override default timeouts on a per-command basis ?

Thanks,

**Comment by mayuresh82** [comment]
hey @fdebonneval missed this issue. Is this still a problem for you ?

**Comment by fdebonneval** [comment]
Yes, it still is ...


Thx

Le ven. 14 juin 2019 à 23:20, mayuresh82 <notifications@github.com> a
écrit :

**Comment by mayuresh82** [comment]
this is now doable via #64   
you can now specify a global collector-timeout which will apply to all commands.
Sorry it took only about a year to do :)
