### ISSUE TITLE
license information missing

### ISSUE THREAD

**Issue by dpajin** [dgarros/py-metric-collector#60]
Hello everyone, 

Thanks for sharing this nice project. Would you consider adding license information to the project, so that is clear how this project can be used? 

Many thanks, 
Dusan

**Comment by mayuresh82** [comment]
What do people think the license should look like ?

**Comment by dpajin** [comment]
Hi @mayuresh82, @dgarros,

is there any chance that you provide some feedback on my question? Thanks.

**Comment by dpajin** [comment]
I see now that license information is available in `setup.py` file, so closing the issue
