### ISSUE TITLE
metric collector container exits with error: unrecognized arguments: --console

### ISSUE THREAD

**Issue by Vuader** [dgarros/py-metric-collector#61]
With commit 4f27631aeaf5a6d476c192bf9b7b8fe4b2fbac2a
The py-metric-collector_metric-collector container immediately exits with:

`error: unrecognized arguments: --console`

[Here](https://github.com/dgarros/py-metric-collector/blob/4f27631aeaf5a6d476c192bf9b7b8fe4b2fbac2a/docker-compose.yml#L25) we see `--console` in the `docker-compose.yml` file , but it’s [not available as an argument in the cli](https://github.com/dgarros/py-metric-collector/blob/4f27631aeaf5a6d476c192bf9b7b8fe4b2fbac2a/lib/metric_collector/cli.py#L188-L226)

Removing that line from the `docker-compose.yml` allows the container to keep on running

**Comment by mayuresh82** [comment]
thanks, yes that arg is no longer valid . Fixed via #62
